export default {
  FETCH_START: "FETCH_START",
  FETCH_ERROR: "FETCH_ERROR",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  POST_PRODUCT_SUCCESS: "POST_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS"
};
